services:
  - type: web
    name: user-management-service
    env: docker
    plan: free
    envVars:
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: APP_JWT_SECRET
        generateValue: true
      - key: APP_JWT_EXPIRATION_IN_MS
        value: 86400000

databases:
  - name: user-management-db
    databaseName: user_management_db
    user: user_management_user
    plan: free
