spring.application.name=notification-management-service

# Email Configuration
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:lankevenkatesh314@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:gfap dwkm huyl bgau}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# WhatsApp Configuration (Twilio)
twilio.account.sid=${TWILIO_ACCOUNT_SID:your-twilio-account-sid}
twilio.auth.token=${TWILIO_AUTH_TOKEN:your-twilio-auth-token}
twilio.whatsapp.from.number=${TWILIO_WHATSAPP_FROM_NUMBER:+14155238886}

# Server Configuration
server.port=8085
