spring.application.name=user-management-service

# Database Configuration (Production - PostgreSQL)
spring.datasource.url=${DATABASE_URL:postgresql://localhost:5432/user_management_db}
spring.datasource.username=${DB_USER:user}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never

# JWT Configuration
app.jwt.secret=${APP_JWT_SECRET:mySecretKeyForJWTTokenGenerationWhichShouldBeLongEnoughForHS512Algorithm}
app.jwt.expiration-in-ms=${APP_JWT_EXPIRATION_IN_MS:86400000}

# Server Configuration
server.port=${PORT:8081}
server.servlet.context-path=/api/v1

# Logging
logging.level.com.venkatesh.it.usermanagementservice=INFO
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=WARN
